In [5]:
import numpy as np 
arr = np.array([[11,12,13,14],[15,16,17,18]])
print(arr)

[[11 12 13 14]
 [15 16 17 18]]


In [12]:
arr2 = np.array([[0,0,0],[0,0,0],[0,0,0],[0,0,0]])
print(arr2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
